### ISSUE TITLE
Package.json missing ending / closing curly bracket.

### ISSUE THREAD

**Issue by saas786** [tomaszbujnowicz/laravel-mix-tailwindcss-purgecss#1]
Last commit deleted it accidentally.

https://github.com/tomaszbujnowicz/laravel-mix-tailwindcss-purgecss/commit/7f973c41035964158cdf6120f0b6fd8bf80c35b0

**Comment by tomaszbujnowicz** [comment]
Fixed with the following commit https://github.com/tomaszbujnowicz/laravel-mix-tailwindcss-purgecss/commit/d3e09a37d2218348ea47c44c95bdc46b6e58c0f3
