### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by pasqualevitiello** [tomaszbujnowicz/laravel-mix-tailwindcss-purgecss#3]
Very cool boilerplate! Any plans to provide Sass support?

**Comment by tomaszbujnowicz** [comment]
Thanks for your kind words.
I use only TailwindCSS and there is no need to mix it with Sass these days.
I am planning to keep that boilerplate as minimal as possible so no plans for Sass support.
But it's relatively easy to add that support to the boilerplate, here is a little guide https://laravel.com/docs/7.x/mix#sass

Hope it helps ;)
